### PR TITLE
fix eslint

### PR DESCRIPTION
**Pull request by Mecrano**
**What problem is this solving?**

Hello, the .eslintrc file was being ignored by Github since it was in the exclusion list (.gitignore), this caused that when you wanted to make a commit the husky would throw the following error:
"error Parsing error: The keyword 'import 'is reserved"
additional eslint was not extending correctly from" VTEX "package

**How should this be manually tested?**
try to make a commit when one of your files import any other file o package

**Screenshots or example usage:**

image

### CODE REVIEW

**Comment by Mecrano** [comment]
> Beep boop 🤖
> 
> I noticed you didn't make any changes at the `docs/` folder
> 
> * [ *]  There's nothing new to document 🤔
> * [ ]  I'll do it later 😞
> 
> In order to keep track, I'll create an issue if you decide now is not a good time
> 
> * [ ]  I just updated 🎉🎉

**Comment by Mecrano** [comment]
sry but i cant select any opcions of bots :(

**Comment by Mecrano** [comment]
@kevinch Hi, i fix one thing, you can reviews ple? have a nice day :)

**Comment by kevinch** [comment]
Hey @Mecrano i just merged several PRs of dependabot and saw that no file was being updated anymore in your PR. Looks like the gitignore is fine now at the root: https://github.com/vtex-apps/admin-example/blob/master/.gitignore

**Comment by kevinch** [comment]
Closing as we just updated the repo and removed danger from it.

**Pull request closed without merging**
